name: final_project
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  google_fonts: 5.1.0
  flutter_staggered_grid_view: 0.7.0
  readmore: 2.2.0
  iconly: 1.0.1
  firebase_core: ^2.16.0
  cloud_firestore: ^4.9.2
  firebase_auth: 4.10.0
  flutter_svg: 2.0.7
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/icon/
  uses-material-design: true

