// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD08Vrmw8Ve8H5eAkwg4QRyAJ4_ZXHWroM',
    appId: '1:166768641741:web:fc60053fb55c403c424b84',
    messagingSenderId: '166768641741',
    projectId: 'finalproject-29b9e',
    authDomain: 'finalproject-29b9e.firebaseapp.com',
    storageBucket: 'finalproject-29b9e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHScpL2VDDDA7kXilD94dKj1uVTo6d9UQ',
    appId: '1:166768641741:android:4d6e49c793aa5bd1424b84',
    messagingSenderId: '166768641741',
    projectId: 'finalproject-29b9e',
    storageBucket: 'finalproject-29b9e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7aCpOFy9i_Z1b0GMS1S7hAphUmerStb0',
    appId: '1:166768641741:ios:847428a40d305581424b84',
    messagingSenderId: '166768641741',
    projectId: 'finalproject-29b9e',
    storageBucket: 'finalproject-29b9e.appspot.com',
    iosBundleId: 'fardz2.netlify.app.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7aCpOFy9i_Z1b0GMS1S7hAphUmerStb0',
    appId: '1:166768641741:ios:00395492ff801d86424b84',
    messagingSenderId: '166768641741',
    projectId: 'finalproject-29b9e',
    storageBucket: 'finalproject-29b9e.appspot.com',
    iosBundleId: 'fardz2.netlify.app.finalProject.RunnerTests',
  );
}
